#+TITLE: gdowding
#-DESCRIPTION: Programming, Music, Etc.

#+STARTUP: logdone

#+URL: http://gdowding.github.io
#-TEMPLATE_DIR: templates
#+PUBLISH_DIR: .
#+FILENAME_SANITIZER: ob-sanitize-string
#+POST_SORTER: ob-sort-posts-by-title

#+POST_BUILD_SHELL: cmd 1
#+POST_BUILD_SHELL: cmd 2
#+POST_BUILD_SHELL: cmd 3
#+POST_BUILD_SHELL: cmd 4

* gdowding writes
  :PROPERTIES:
  :PAGE: index.html
  :TEMPLATE: blog_static_with_recent.html
  :END:

* TODO Blogging on Git using Org mode
** install emacs
** git clone o-blog
** create a blog
** What I like about it
*** Easy to use once set up
*** seems to integrate well with org mode
    I'll have to use it for a while to see if I like this, but for now, it
    seems to be pretty easy to use which is one of my goals.
** issues
*** o-blog dependencies adoc, ???, and htmlize
*** getting started fully documented
*** one big file?
    Is it possible to put posts into separate files. Also is it possible to
    generate files incrementally or is the whole site rebuilt every time? Not
    sure if blogging with Jekyl is any different. Could be a weakness of org
    mode or maybe solved with a make file.
*** Not that obvious how to have current blogs show up in index

*** some errors not reported
    for example, when I had an error in a template, there was no error when
    publishing, but it showed up on the web page as an error.
** customization
*** creating a main page with links to recent articles
+ modified the blog_static.html template to include a section that creats a list of the most recent (last 5) posts
+ example code from here http://renard.github.io/o-blog/functions.html
** TODO figure out how to get the first paragraph or summary of the blog post
** TODO figure out how to upload to github
** TODO skip including the main page

* TODO A New Computer for Music Production

Started looking for a laptop that I could install linux on a bit more
seriously today. I'm looking at a Lenovo T430. My main questions are
on which processor to buy. I am not looking to spend excessive amounts
of money, so if I don't need to upgrade that is better.

My baseline is a Mac mini which I use NI Machine, and occasionally
Ableton, Reaper or Renoise. Moving forward, I'd like to use open
source software. I have some interest in the software side of digital
music production. Maybe that is a distraction from actually making
music. I'm also have a bit of outboard gear now, so I expect I'll be
doing some more production OTB, but would like to have something to
compliment the outboard gear as well as have something portable.

I was surprised to find out my min has a 2.7 Ghz Intel Core i7. It
seems to get over worked fairly easily even when not producing music.

I think for now I am going to go with the T430 and get linux
installed. In the mean time, I need to understand what the bottlenecks
are with the mini.

One area I've identified is that loading projects in Machine seems to
take a while (couple of seconds). I suspect an SSD will make a
significant improvement in this area.

In the end I bought a 13" MacBook Pro customized with 16G Ram, 2.8 GHz
Intel Core i7, and 500GB SSD. I am mostly ok giving up propriatary software
even non-Linux software, but I couldn't really find a laptop that was built
like the MacBooks. The new ones are portable and sturdy. One could probably
get better specs buying a PC based laptop, but build quality is important
enough for me (and I am lucky enough to afford it at the moment) to pay extra
for Apple and forgo more resources under the assumption that the MacBook Pro is
sufficient. Also I have a Thunderbolt display that is basicaly useless with
anything but an Apple system. I could probably sell it, but would take a loss.


However, I feel that this is the last time I will buy an Apple and run OSX.
This laptop shold be sufficient for the next couple of years, during that time,
I plan to build a linux desktop for the purpose of migrating all personal
work and music production and do all music production on Linux (maybe even
open source) software. Currently the non-open source software that I might be
using are Renoise, maybe Bitwig. But I don't currently own a Bitwig license,
so maybe not.

* TODO Setting up github blogging
** switched to o-blog
** after some basic configuraiton, it just worked
   generate the pages using o-blog and git push

* Snippets

** Navigation
   :PROPERTIES:
   :SNIPPET:  t
   :END:

** About
  :PROPERTIES:
  :SNIPPET:  t
  :END:
   
** Navigation Footer
   :PROPERTIES:
   :SNIPPET: t
   :END:

** Copyright
   :PROPERTIES:
   :SNIPPET: t
   :END:

George A. Dowding 2014
