#+TITLE:       New Year New Blog
#+AUTHOR:      George Dowding
#+EMAIL:       gdowding@sidgel.local
#+DATE:        2016-01-02 Sat
#+URI:         /blog/%y/%m/%d/new-year-new-blog
#+KEYWORDS:    emacs,org,org-page
#+TAGS:        emacs,org,org-blog
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Getting started on blogging for the New Year with org-page
* Why blog with emacs org?

Foo

I do most of my work in emacs and prefer to do any writing in
org-mode. It fits my way of working with source and building a
product. I'm already taking lots of notes in emacs org-mode. I am
hopeful (new year and all) that I can convert these to actual blogs
and articles. Finally, since it is logargely based on elisp, it can
all be customized. In practice, I haven't spent much time doing any
serious elisp customization. Again, I'm hopefull that I can spend some
time automating common programming and writing tasks.

Also leverages git.

* About org-page

* Install org-page
I use a combination of git and cask to manage emacs packages. I
usually use Cask to do the initial install which takes care of all of
the dependencies then clone the repository in case I need to read or
modify the code.

#+BEGIN_EXAMPLE
(depends-on "org-page")
#+END_EXAMPLE

I already had a github

* Initial setup

** Need source and master

A little weird

** Basic customization

#+BEGIN_EXAMPLE
;; Blog with org-page
(require 'org-page)
(setq op/repository-directory "~/git/gdowding/gdowding.github.io")
(setq op/site-domain "http://gdowding.github.io")
(setq op/personal-github-link "https://github.com/gdowding")
(setq op/site-main-title "In the Ocean")
(setq op/site-sub-title "")
(setq op/theme 'phaer)
#+END_EXAMPLE
